### ISSUE TITLE
attack monster

### ISSUE THREAD

**Issue by Marco9579** [PaimaStudios/tarochi-game#102]
You are attack by monster when you are in the menu team and item so you can change the monster place if you need and when I want swap the position of monster I can't

**Comment by acedward** [comment]
Yes, as the game is decentralized and the blockchain doesn't know you are on a menu. So it generates wild monster battles.

We will take care of this in the future.

**Comment by Marco9579** [comment]
thank you for the answer and the position changes of pokemons for battles are not often taken into account...
