### ISSUE TITLE
Excavation card did not used during excavation

### ISSUE THREAD

**Issue by SSvystun** [PaimaStudios/tarochi-game#104]
When user perform excavation card and found excavation card - excavation card for that try will be not used 

https://github.com/PaimaStudios/tarochi-game/assets/66019349/1ea13240-e20b-4511-b0fd-306f0e418b97

As example - user has 2 card, started excavation, and found excavation card 
There was 2 card - 1 used + 1 received = 2 
But after excavation user has 3 cards

**Comment by acedward** [comment]
This is a strange bug!
Thanks for the report!
I will look into it ASAP

The fonts look very strange. 
Have they always looked like that?

**Comment by SSvystun** [comment]
No idea why it happens, now it looks normal 
When find reproducible scenario for that - will let you know
