### ISSUE TITLE
User is not able to leave excavation area 

### ISSUE THREAD

**Issue by SSvystun** [PaimaStudios/tarochi-game#105]
When user goes to the NPC, skip all the conversation and press "Q" for exit, then try to leave Excavation area - he is not able to do it, because after confirming transaction nothing happens - "waiting for transaction confirmation" message didn't appear
Issue can be solved only via reloading the page, any buttons doesn't work in this state 

https://github.com/PaimaStudios/tarochi-game/assets/66019349/866b41e8-27a6-40fb-b9c1-310c29351a51

**Comment by acedward** [comment]
fixed
