### ISSUE TITLE
User received Deepsand Excavation area on map after visiting Deepsand Valley 

### ISSUE THREAD

**Issue by SSvystun** [PaimaStudios/tarochi-game#107]
![зображення](https://github.com/PaimaStudios/tarochi-game/assets/66019349/9f8a8fea-6176-4825-bb30-5abb52f77cc1)
I'm not sure if ti's expected, but user is able to perform fast travel to the Deepsand Excavation area without visiting this area before. 
I visited Deepsand valley, died there, and now I'm able to perform a fast travel to the Deepsand Excavation area.

**Comment by SSvystun** [comment]
@acedward Update: 
User is able to make a fast travel to the excavation area WITHOUT beating defender of entry to the Deepsand Excavation area 

Basically user is able only teleport to this area, after leaving - he is not able to visit it again via entry, only via fast travel

**Comment by acedward** [comment]
Ohh thanks!
I have looking for this bug for so long

**Comment by acedward** [comment]
Fixed on next release
