### ISSUE TITLE
Russian translation of tarotchi 

### ISSUE THREAD

**Issue by Yuno266** [PaimaStudios/tarochi-game#110]
![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/cead8b3b-352b-4a43-b045-bfc11802e471)

The rarity of the monster is translated in the Command and Items tabs, but not translated in the Storage Box

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/8fe6094c-98da-4e0a-bebc-5414df5b5560)

The translation of the word 'Victory' is missing in battles with wild monsters, but it exists in battles with NPCs.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/8ffe4ffc-a959-4749-b12b-0e04d928d346)

A word that isn't even in the table has been inserted where there shouldn't be any words.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/13b07e8e-e177-4c7c-8371-e2547e00ba15)

When confirming the transaction, the word "Use" is not translated.
Submitting transaction 'Use Epic Whitelist capture card' when transaction confirmed and transaction in progress.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/fbc3a4e3-7145-407f-9df6-35fe66d8631b)

The translation of the location is missing.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/3541d40f-6c9d-4bc7-8d0d-bca503a10564)

The translation of '_tx_failed' is missing for transaction errors.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/7cc52086-f8e8-4548-95c9-ed7c5068e207)

If possible, do not translate battle logs. Also, add a space after 'affected by'.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/ecc93d69-0696-43b4-ad6c-36d14e89e00c)

The name of the location that appears in the top left corner when visiting the location is not translated.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/92257669-b12d-4aef-ad91-2976a55df776)

The rarity of the item obtained from excavation is not translated.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/71792f4a-a318-413e-a75d-b1942f2775eb)

"Barter" is not translated upon confirming the transaction.

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/96f8fa1d-c894-48f7-ac50-54df3b9241a4)

The Arena rules sign is not translated.

**Comment by acedward** [comment]
Amazing help 🙏 
This was very useful. Almost all fixed.


I'm not sure about this. What does it say?
<img width="565" alt="image" src="https://github.com/PaimaStudios/tarochi-game/assets/3951895/4078d77d-27a7-4ce5-a8b0-20f8093d2e5f">

What do you mean by:
> If possible, do not translate battle logs.

**Comment by Yuno266** [comment]
> not

It shouldn't have had any extra text, it's fixed now, but a new problem has appeared. There's an extra symbol in the 'Stamina' tab.
![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/6cf75cd0-99ff-4f93-9693-7387788920d1)

**Comment by Yuno266** [comment]
"Rareness" and "Monster color" are not translated into English in the "Stored" tab within the storage box.
![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/d6c08a7d-b02a-40d1-907d-d34afb74e471)

The location name in the top left corner - "missing text".
![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/af37c0e7-8ff2-411e-818d-9ea09d019f6a)

During fusion, the translation for "yes/no" is missing
![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/96516c1b-107a-4ada-9855-98abb288c483)

![image](https://github.com/PaimaStudios/tarochi-game/assets/115049663/1bccfebb-b99c-4495-9a59-a310378fd08d)
In the achievements, the opponent's name and their Tarot card are mentioned. In Russian, the name "Luna" is translated as "Луна," which can cause confusion since "The Moon" is also a Tarot card. It would be preferable to enclose Tarot cards in brackets in the achievements. For example: "Defeat Luna [The Moon] at Bayshore."

**Comment by acedward** [comment]
<img width="625" alt="image" src="https://github.com/PaimaStudios/tarochi-game/assets/3951895/d00e928a-7b82-4d1a-9753-fe5f654cb055">


Yes / No are integrated into the image. This will take more time to fix.
