### ISSUE TITLE
Game function bugs

### ISSUE THREAD

**Issue by stingysaffa** [PaimaStudios/tarochi-game#114]
1) Can not unlock stonerise POI. Get all the way to north yellowtree cave and transports me back to south entrance.

2) Monsters not matching my level, my lvl 16s are vsing lvl 10 at sunnypath for example. Gaining minimal to 0 exp per fight. 

3) Defeating fortuna at rockpath cave does not open the gate.

**Comment by acedward** [comment]
Thanks for reporting! We will look  into this. The yellowcave issue looks critical.

**Comment by stingysaffa** [comment]
any fixes yet?

**Comment by acedward** [comment]
(1) was fixed 
Investigating 2

**Comment by stingysaffa** [comment]
Might be worth noting - problem 2 only occurs in some poi’s such as sunny path, deep sand and rock path cave . Others match my level , (also thanks yr the goat)

**Comment by acedward** [comment]
Fixed
