### ISSUE TITLE
Resetting burner wallet flips player & opponent places in the UI

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#14]
A player recovered their wallet by clearing their local storage and then connecting a new burner wallet to their Flint wallet

> It seems after recovering my wallet im always as an enemy team 👀

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/71ede17d-ddca-48f6-b78d-f8bfeb7dd19a)

**Comment by acedward** [comment]
Fixed, game frontend was using the local wallet for calculations.
