### ISSUE TITLE
Make guild point update more explicit

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#143]
Right now the Guild Genesis Trainer updates every 24hrs. However, a lot of people are not realizing this. We should try and make this more obvious for the UI since it will help avoid a lot of these support tickets

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/5cdef310-1d0e-4cc1-bb7b-e8400e27d8cb)

**Comment by acedward** [comment]
I can add updates on:
1 Member Join
2 Member Leaver
3 Some buttons in the options to recalculate (For all guilds)
4 Each 24 hours
(we are not monitoring the transfer event for monster cards)
