### ISSUE TITLE
Buff Florawing SATK

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#153]
Florawing has really low SATK so their special attacks almost never land. It's much lower than other legendaries

It's kind of strange is has both low SATK & low ATK with no other stats to make up for the difference

Here is a comparison with other legendaries (all are lvl 18 in this screenshot)
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/58cd7363-6b34-436f-aa64-b6df83294b61)

**Comment by acedward** [comment]
Duplicate #189
