### ISSUE TITLE
Investigate game speedup

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#182]
Assuming every step is instant with emulated blocks = 1s, it should take at most ~2 seconds for the full end-to-end from a user submitting a move to the result being seen in the user's frontend. However, in practice, they take longer which means there is a lot of overhead that we can cut down on

Example flow of 2 transactions:

monster swap
```
0.0  Request Send to Batcher
1.30 Request Accepted By Batcher
2.30 Batcher Build TX
4.50 Processed By Paima Engine
6.0  Last Track User Input Called Finished
8.1  Fetch user completed (to update state)
```

attack in a round
```
0.0 Network Request Send to Batcher
0.60 Request Processed By Batcher
5.80 Batcher Build TX
8.50 Processed By Paima Engine
10.7 Last Track User Input Called
13.8 Other Fetches to Update State Finished
```

**Comment by acedward** [comment]
duplicate #151
