### ISSUE TITLE
Heal ability target mismatch

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#20]
When using heal, the text said "sparkcell" but the heal animation appeared on the front monster

Then, it showed my health being above the max health in the "party" page (in battle it still showed 70/70, but in practice getting hit proved that the healthbar actually was higher than 70/70)

**Comment by acedward** [comment]
fixed the bar not going over 100%

**Comment by acedward** [comment]
<img width="870" alt="image" src="https://github.com/PaimaStudios/tarochi-game/assets/3951895/66e3dbf7-b4b2-4bc0-9421-d1437c57bd29">
