### ISSUE TITLE
Fast travel map issues

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#202]
Two recent issues reported with the fast travel

1. Wrong current locations

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/a976a4d0-cb8b-4640-b6da-9d5058dcbf56)

2. Bayshore shown as locked, even though they _are_ in Bayshore

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/5dde3494-07ab-40a5-9909-6620a6c758d4)

**Comment by acedward** [comment]
Fixed
