### ISSUE TITLE
Implement max price cap for quests

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#203]
Right now people can list quests for really high TGold amounts. It's a kind of scam where you hope the person doesn't notice the amount and accepts anyway.

I don't know how likely somebody is to fall for this, and it's not clear what a "max price" should be (maybe capped by the TGold prize of completing the quest, which monster quests being normalized to TGold via whitelist capture card prices), but I'm creating this issue just to track this request

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/0639d1cf-dd5c-4bcd-b2f3-9f7a4a8a2a8d)

**Comment by acedward** [comment]
Limit Max Price of Quest (to 100% of with gold prize, or 2x the equivalent cost of capture cards)
