### ISSUE TITLE
Make the store in the city more obvious

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#33]
Many players went through the game without knowing how to purchase capture cards according to the stats.

One of the players told us they just never ended up talking to this NPC. We should maybe make it more obvious. Open to ideas on this

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/8c830a6e-74f2-4ad8-9ed2-61fb3f9523f0)

**Comment by acedward** [comment]
Fixed @ Season 1
