### ISSUE TITLE
Monster typo in bag page

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#36]
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/f3a9329b-b896-4b2e-b549-b461cf9e119a)

Defeat spelling
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/082d4477-7f28-4a5c-a085-60a78e55a314)

Resurrection spelling
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/25c21afc-a011-43c1-b234-248102dad952)

`in in`
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/04a36729-6f95-4abf-9d86-41ee4577006a)

**Comment by acedward** [comment]
Fixed Season 1
