### ISSUE TITLE
flutterclaw balancing?

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#60]
I didn't check the monster stats, but I noticed this conversation on Discord
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/5e6f9198-1866-4c1b-930f-02bab66637da)

![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/c4baf373-9420-4d2e-9629-b85134b66e56)

**Comment by acedward** [comment]
I've seen some monsters and attacks quite unbalanced, monster stats and attacks were all built based on normal distributions, but there might be some untested combinations.

I'm working on a simulator to balance monsters/attacks.

**Comment by acedward** [comment]
Also in #88
