### ISSUE TITLE
Exchange for buying & selling TGOLD from Arbitrum One

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#67]
Note: I'm creating this here for now, but it will probably have to move to https://github.com/PaimaStudios/PRC later

TGOLD is the main currency in the Tarochi autonomous world, so naturally people want to buy & sell it. However, Tarochi acts a L4 (on top of Xai) meaning it is not directly connected to Arbitrum One. However, since all the liquidity is on Arbitrum One, we want to ensure people can trade from there.

**Requirements**
- Can buy & sell directly from Arbitrum One (no need to bridge funds)
- Does not require a centralized actor (buyers pay the sellers directly)
- Handles concurrent orders gracefully
- It has to be realistic for people to self-run the infrastructure if they don't want to trust the website / light clients

## Approach overview: it's not an AMM

In a typical AMM dex, there are liquidity pools and you trade against these pools. This is not possible for us because a contract on Arbitrum cannot know the state of the Tarochi L4 so the contract cannot automate market making. Instead, buyers have to be sending tokens directly to the sellers.

The main challenges with this approach are the following:
1. How to know if an order is not fulfilled yet? We cannot have a centralized entity be refunding people if they tried to buy an order that no longer exists.
2. How to everyone trying to buy the same sell order at once (causing 1 tx to succeed, and all others to fail causing a lot of waste on gas cost)

## How do we achieve this

The flow looks like this:

1. We create a smart contract on Arbitrum to facilitate trading TGOLD. This contract allows the following
    1. Function to create a sell order. A sell orders persist and have the following properties: `<id, address, amount, sell price>`
    3. A `cancel` order to cancel a sell order
    4. A buy function. There is no "buy order" that persists, and rather the buy function has the following `<ids[], address, amount>`. Buying removes all the sell orders it fulfills.
2. Have Tarochi monitors this contract using CDEs and exposes an API to query its state

That is to say, the Arbitrum contract has no way of knowing if somebody who makes a sell order really has that amount of TGOLD in their account. Rather,
1. When somebody creates a sell order: Tarochi sees it and checks if the user has enough TGOLD in their Tarochi account.
    2. If yes, the amount is locked so they cannot spend it in-game (unless they cancel the order)
    3. If not, the order is marked as invalid (to differentiate it from the case where it doesn't know the order exists yet)
2. When somebody wants to buy, they specify the amount they want to buy and the server finds all the sell orders to aggregate to fulfill their order (more similar to an orderbook DEX than an AMM). The user then makes a smart contract call that fulfills all the orders and sends the right amount to the corresponding accounts in a single transaction (atomic)
3. Tarochi monitors the successfully fulfilled orders and transfers the TGOLD value between accounts

Some important notes to mention:
1. All actions (sell, buy, cancel) are done in Arbitrum (and not in Tarochi). This allows Arbitrum to be the source of truth for the state of which orders are valid which avoids double-spends. That is to say, if you try and perform a buy order, you are guaranteed by Arbitrum itself that the order hasn't been fulfilled by anybody else yet
2. Extra work will be done to avoid excessively many failed transactions (everybody trying to buy the same sell order).

### Avoiding many failed txs in this model

The problem with this model is people will naturally all try to buy the order with the most favorable sell price. Arbitrum has fast blocks so collisions are not so likely _if_ the UI updates fast enough, but if bots start trading good orders as soon as they appear it may cause a rush with many failed txs. 

#### Option 1) A L3 for all games

However, the key observation is that solving this concurrency issue does not need any knowledge of the game itself (it doesn't matter if orders are valid or not from the dApp perspective. It just assumes buyers are not making bad purchases).

This is an important note because it means we could have a decentralized L3 on top of Arbitrum whose goal it is to match orders properly and that could cover multiple games and not just Tarochi. Notably, there is a model that provides exactly what we want with no tx fee if concurrent actions are attempted like this: the utxo model. That is to say, implementing this system on top of Cardano (Aiken) or Fuel is actually much easier than the account model. However, Arbitrum users of course cannot be using Cardano, so this would most likely require running a Fuel L3 for Arbitrum (or maybe some ZK-ified UTXO platform if one exists) where the validators are decided by the Paima ecosystem token

Although I do think this has potential, it falls short on a few key points:
1. It would require adding Fuel support to Paima Engine to properly monitor it
2. It would require the Paima ecosystem to be released (not released yet)
3. It means we lose some composability with other Arbitrum dApps (unless Fuel adds a wrapped smart contract system like Milkomeda)
4. Users may be hesitant to bridge to this L3 just to trade, so we would have to abstract this away from them (again, wrapped smart contracts may help in the optimistic case where there isn't a conflicting order so they can buy TGOLD right away)

Given the complexity, and our timeline, we can't implement this fast enough for users to be satisfied. 

#### Option 2) Stylus

Arbitrum recently introduced a new programming language called [Stylus](https://arbitrum.io/stylus) which is much faster & cheaper than EVM. Additionally, it's composable with EVM contracts so you do not run into the same composability tradeoffs as with L3s. However, as far as I know, it can't solve the concurrent issue entirely like the UTXO model. Rather, it might just make the gas cost of failing cheaper (which maybe is enough for now). Additionally, it's not live on mainnet at the moment

#### Option 3) Frontend-driven concurrency management

Solving in the short term is not so hard if there is only a single website for the DEX because the website itself can keep track of orders people are attempting to make to avoid conflicting orders being placed. However, this will quickly fall apart if another website appears or if people start making trades directly to the contract.

**Comment by acedward** [comment]
* PRC-5 Draft https://github.com/PaimaStudios/PRC/pull/8/files
* Paima-Engine ERC1155 CDE is required to implement
* Implement Frontend UI to Lock/Unlock
* Implement Backend
