### ISSUE TITLE
Might Be Monsters Nearby Doesn't Trigger Battle Room Change [Frontend]

### ISSUE THREAD

**Issue by robkorn** [PaimaStudios/tarochi-game#73]
I've seen this from a couple people, they had to refresh their browser because they got this message and the room never changed to the battle room. Seems like frontend isn't checking for the battle for some reason (or maybe an edge case).

![image](https://github.com/PaimaStudios/tarochi-game/assets/11645932/ecee400b-20de-49ad-8254-9c2d0d29e5d9)

**Comment by robkorn** [comment]
![image](https://github.com/PaimaStudios/tarochi-game/assets/11645932/68e2aa64-98c3-46c3-99b7-ac64bb919b30)

**Comment by acedward** [comment]
Merged with issue #61
