### ISSUE TITLE
Monster Fusion Bug

### ISSUE THREAD

**Issue by acedward** [PaimaStudios/tarochi-game#78]
If fusion is used one of these two cases happens:

Monster earns enough XP to Level UP:
* Set XP at 0, Level++, Max Level++, Fusion Count++

Monster does not Level UP:
* Gains XP 
In this second case, Max Level and Fusion Count do not go up as expected.

But players are always getting the correct XP bonus

**Comment by SebastienGllmt** [comment]
Some other comments on fusion I've seen (I haven't verified these)

- > my flutterclaw got fuse 0 after i fusion it to fuse 5 now it cannot fuse anymore and stuck at 0.
- > BUG: When fused, the max level won't increase when the initiating pet is in the front position
