### ISSUE TITLE
Overlay stays open if battle starts while it's loading

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#79]
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/60af9a9a-13b0-46fb-8479-aba0dff1dd89)

**Comment by pmartinez85** [comment]
It happens with any action you are doing. If you travel or use and object(potion) and a wild monster appear starting the battle, the previous action is canceled. Travel is canceled and you lose the item.
