### ISSUE TITLE
Fix fusion bugs

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#82]
Right now a lot of people are complaining fusion is broken. I'm not sure exactly what the error is, but we need to either:
1. Fix the bug (if it's a bug)
2. Explain the system better (if it's not a bug)

The main complaint I've seen is that the fusion count is not increasing properly

**Comment by acedward** [comment]
https://github.com/PaimaStudios/tarochi-game/issues/78
