### ISSUE TITLE
Crossroad pass map wall bug

### ISSUE THREAD

**Issue by zwardenz** [PaimaStudios/tarochi-game#84]
Map: crossroad pass
I defeated all the trainer here and this wall still here
![Screenshot_2024-02-19-20-07-00-092_com android chrome](https://github.com/PaimaStudios/tarochi-game/assets/160499902/09a11bdc-5c46-4d21-94ef-e956f49d63f9)

**Comment by acedward** [comment]
Thanks! It was incorrectly setup.
Fixed in next release :)
