### ISSUE TITLE
Better explain wallet connection needs to be done in the main screen

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#89]
We added the new error message in-game when you try and connect a wallet that already has progress. However, a few people get confused and just keep connecting new wallets to the game over and over again, not realizing they should be restoring their wallet on the main login screen

We should think of a better way of conveying this
![image](https://github.com/PaimaStudios/tarochi-game/assets/2608559/9a49ab3b-b1f8-450d-9058-9a72c0c8519e)

**Comment by acedward** [comment]
messages improved
