### ISSUE TITLE
Split any large files into chunks

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/tarochi-game#99]
Large files cause a lot of issues with caching. Any time we have large file, it should be split up into parts similar to what tools like Webpack do

**Comment by acedward** [comment]
Gamemaker requires to select the file(s) that will be connected with the game. I think it's not possible with dynamic files. It packs this file into its distribution bundle.

<img width="1655" alt="image" src="https://github.com/PaimaStudios/tarochi-game/assets/3951895/fed44011-c862-4406-8361-8b772529d1f1">
